web:
  port: 9950 #api 端口
  ip: "127.0.0.1"
  ip_admin: "127.0.0.1"
  port_admin: 9960 #页面端口
  debug: false
  run_mode: ""
log:
  info:
    filename: "./storage/logs/info.log"
  error:
    filename: "./storage/logs/error.log"
cron: false
storage:
  upload: "./storage/uploads"
  download: "./storage/downloads"
redis:
  host: "127.0.0.1"
  port: 6379
  password:
  db: 0
llm:
  model: "" #模型名称 火山引擎
  base_url: "" #接入地址
  token: "" #token
mysql:
  mysql:
    user: "dev"
    port: 3306
    password: ""
    host: ""
    database: ""
  mysql_read_list:
    - user: "dev"
      port: 3306
      password: ""
      host: ""
      database: ""
